-- 코드를 작성해주세요
SELECT c.ID , b.FISH_NAME, c.LENGTH
FROM FISH_INFO as c
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
    FROM FISH_INFO 
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) as a 
     ON c.FISH_TYPE = a.FISH_TYPE
     AND c.LENGTH = a.LENGTH 
     JOIN FISH_NAME_INFO as b
     ON c.FISH_TYPE = b.FISH_TYPE 
     WHERE c.LENGTH IS NOT NULL
     ORDER BY c.ID;